name: CI/CD Pipeline for Cliniq(PBL-II Project)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 3: Install backend dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Lint/Test (optional)
      - name: Run tests
        run: |
          echo "No automated tests yet"

      # Step 5: Prepare frontend (host-it-html)
      - name: Prepare static frontend
        run: |
          echo "Frontend is static (HTML/CSS/JS) — no build step required"

      # Step 6: Verify database connection (optional)
      - name: Check MySQL Connection
        run: |
          node -e "require('./database'); console.log('Database connected!')"
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}

      # Step 7: Deploy to production server (via SSH)
      # - name: Deploy to Server
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       cd /var/www/your-app-folder
      #       git pull origin main
      #       npm install --production
      #       pm2 restart all
